### ISSUE TITLE
Xcode 12 beta 2: positions are messed up, in the sample app as well

### ISSUE THREAD

**Issue by quantamrhino** [kieranb662/Sliders-SwiftUI#3]
Using Xcode 12, beta 2
I tried overflowslider and radial slider in my sample app and positions were messed up:
- overflow: the tick view and the slider rectangle went off screen never to be shown again till the view was redrawn.
- radial slide / knob - the small circle is not bound by the circle and quite off.

Attaching screens from the sample app (on SE 1 simulator).
Since the gifs on the https://github.com/kieranb662/SlidersExamples page look different, I'm filing this bug.
<img width="316" alt="Screen Shot 2020-07-21 at 12 27 18 PM" src="https://user-images.githubusercontent.com/67089425/88022985-e0a43680-cb4d-11ea-966d-3eb8fc0806f4.png">
<img width="303" alt="Screen Shot 2020-07-21 at 12 26 20 PM" src="https://user-images.githubusercontent.com/67089425/88022990-e26dfa00-cb4d-11ea-8e46-0714d4141a01.png">
<img width="315" alt="Screen Shot 2020-07-21 at 12 26 03 PM" src="https://user-images.githubusercontent.com/67089425/88023000-e568ea80-cb4d-11ea-95a7-60feed43b062.png">

**Comment by kieranb662** [comment]
I just updated the library to reflect the changes to swiftUI in Xcode Beta 12. 

It turns out that `GeometryReader` has been updated to align a single child view using a top-leading alignment rather than the previous centered alignment. 

Please try the example project with the 1.0.10 package and let me know if you have issue.
